apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-application-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: devops-application
  template:
    metadata:
      labels:
        app: devops-application
    spec:
      containers:
        - name: devops-application
          image: merdo9164/devops-application:latest
          resources:
            limits:
              memory: "300Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080


